### PR TITLE
Utilize go install for kind downloading

### PR DESCRIPTION
**Pull request by dmvolod**
This utilizing go install command for go binaries downloading instead of temp go mod init directory

### CODE REVIEW

**Comment by dmvolod** [comment]
Probably it could be easy to utilize `go install $pkg@$version` as go version set to 1.16

**Comment by eguzki** [comment]
First of all, thank you for the contribution. 

I would not use a archived dependency to install dev tools. 

> Probably it could be easy to utilize go install $pkg@$version as go version set to 1.16

I would go for that. `go install $pkg@$version` as well

**Comment by dmvolod** [comment]
Thanks, @eguzki for review.
PR changed to utilizing `go install` command.

**Review by eguzki — APPROVED** [review]

**Comment by eguzki** [comment]
thanks @dmvolod :medal_military:

**Pull request merged**
